package main

import (
	"fmt"
	"math/rand"
	"time"
)

func main() {
	rand.Seed(time.Now().UnixNano())
	first := []string{"Accomplished", "Agile", "Amber", "Anguished", "Anointed", "Apex", "Apprentice", "Ardent", "Aromatic", "Ashen", "Avid", "Barreling", "Bejeweled", "Belligerent", "Bellowing", "Bewitching", "Bitter", "Bloodsoaked", "Bloody", "Blue", "Bold", "Bossy", "Brash", "Brittle", "Brutal", "Bubbly", "Cackling", "Callous", "Carrion", "Charnel", "Clever", "Committed", "Complete", "Consummate", "Covetous", "Crimson", "Crushing", "Crystalline", "Cunning", "Cutting", "Dark", "Dauntless", "Dazzling", "Deadly", "Dedicated", "Desert", "Devoted", "Diabolic", "Diligent", "Dire", "Dirty", "Distilled", "Distracted", "Dogged", "Drowned", "Drunken", "Dry", "Elemental", "Embattled", "Enlightened", "Equestrian", "Equipped", "Essential", "Eventful", "Exalted", "Faithful", "Fallen", "Fanged", "Ferocious", "Fleet", "Foolish", "Formless", "Foul", "Fractured", "Fragrant", "Frost", "Furious", "Giant", "Gilded", "Glen", "Grave", "Grim", "Hallowed", "Hasty", "Hatred’s", "Hellish", "Hermetic", "Holy", "Honored", "Horned", "Howling", "Hungry", "Imbued", "Insatiable", "Intense", "Iron", "Journeyed", "Laughing", "Legendary", "Lethal", "Liminal", "Little", "Local", "Lonely", "Lucky", "Mad", "Magic", "Malicious", "Marsh", "Merciless", "Meticulous", "Mighty", "Murderous", "Murmuring", "Natural", "Necrotic", "Nefarious", "Nocturnal", "Novice", "Overwhelming", "Pained", "Pale", "Pallid", "Paragon", "Peerless", "Potential", "Prepared", "Profane", "Pyro", "Quick", "Rapid", "Rampaging", "Rare", "Ravenous", "Renaissance", "Rending", "Resourceful", "Risen", "Rotten", "Ruinous", "Rusted", "Sacred", "Salty", "Sanctified", "Sanguine", "Scarred", "Seasoned", "Serial", "Shambling", "Sharp", "Shattered", "Shifty", "Sightless", "Silken", "Silver", "Slinking", "Stamping", "Steadfast", "Steely", "Stone", "Succubus", "Sweaty", "Tempered", "Terrifying", "The", "Thorough", "Tidal", "Timeless", "Titan", "Tormented", "Tortured", "Transcended", "Traveled", "Treasure", "Triune", "Twisted", "Unbroken", "Unfettered", "Unflagging", "Unholy", "Unseen", "Upstart", "Vain", "Vengeful", "Venomous", "Vicious", "Vile", "Vitreous", "Voltaic", "Voracious", "Whispering", "Wicked", "Wily", "Winding", "Withering", "Worldly"}
	second := []string{"Abomination", "Acolyte", "Adventurer", "Alchemist", "Apothecary", "Aristocrat", "Armorer", "Armoury", "Aspirant", "Assailant", "Assassin", "Band", "Bandit", "Bane", "Barbarian", "Baron", "Bear", "Beast", "Believer", "Blackguard", "Blessing", "Boots", "Bounty", "Braggart", "Breaker", "Brewer", "Brewmaster", "Brigadier", "Brigand", "Brute", "Butcher", "Catastrophe", "Challenger", "Champion", "Changeling", "Charmer", "Chef", "Chieftain", "Chorus", "Chosen", "Claw", "Cleaver", "Cohort", "Collector", "Combatant", "Commoner", "Comrade", "Conductor", "Conjurer", "Connoiseur", "Conqueror", "Coordinator", "Creature", "Culprit", "Curse", "Cutthroat", "Dancer", "Deadeye", "Deathspeaker", "Delver", "Desolation", "Destroyer", "Devil", "Devotee", "Deominance", "Dread", "Dredger", "Drifter", "Druid", "Dungeoneer", "Eater", "Echo", "Elder", "Enchanter", "Executioner", "Exemplar", "Exorcist", "Explorer", "Fear", "Fiend", "Firestarter", "Florist", "Foe", "Fool", "Fugitive", "Gambler", "Ghost", "Glutton", "Goat", "Guardian", "Harbinger", "Harvester", "Herbalist", "Heretic", "Hero", "Hoarder", "Horadrim", "Horror", "Hound", "Hunter", "Iconoclast", "Immortal", "Imp", "Jeweler", "Jockey", "Killer", "Kindred", "Legend", "Legion", "Lord", "Lout", "Maestro", "Maniac", "Marauder", "Mariner", "Master", "Menace", "Mercy", "Mess", "Miner", "Murderer", "Mystery", "Necromancer", "Nemesis", "Nightmare", "Onslaught", "Opportunist", "Paragon", "Perfumer", "Phantom", "Pirate", "Power", "Predator", "Protector", "Pursuer", "Rage", "Ransacker", "Rapture", "Rat", "Ravager", "Reaper", "Roamer", "Rogue", "Rubbish", "RuinSacrifice", "Sage", "Salvager", "Scavenger", "Scoundrel", "Scourge", "Seeker", "Shaman", "Sheperd", "Shield", "Sinner", "Skinner", "Skull", "Slayer", "Smith", "Sorcerer", "Sovereign", "Specter", "Spellbinder", "Spider", "Spirit", "Stalker", "Striker", "Sunderer", "Supplanter", "Surveyor", "Team", "Tempest", "Terror", "Thief", "Tinker", "Toppier", "Tracker", "Trash", "Traveler", "Trickster", "Trouble", "Tycoon", "Tyrant", "Underdog", "Undertaker", "Vandal", "Vanquisher", "Vapor", "Victor", "Villain", "Vitality", "Voice", "Warrior", "Wayfarer", "Well-Wisher", "Witch", "Wolf", "Wraith", "Wretch", "Zealot"}
	name := first[rand.Intn(len(first)-1)] + " " + second[rand.Intn(len(second)-1)]
	fmt.Println(name)
}
